vich_uploader:
    db_driver: orm

    mappings:
        vehicle_file:
            uri_prefix: '%app.path.vehicles_files%'
            upload_destination: '%kernel.project_dir%/public%app.path.vehicles_files%'
        drivers_file:
            uri_prefix: '%app.path.drivers_files%'
            upload_destination: '%kernel.project_dir%/public%app.path.drivers_files%'
